# Generated by Django 5.0.3 on 2024-05-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('department', models.TextField(max_length=100)),
                ('semister', models.CharField(max_length=10)),
                ('roll_no', models.CharField(max_length=8)),
                ('image', models.ImageField(default='templates/pic1.jpg', upload_to='add')),
            ],
        ),
    ]
